[project]
name = "confluence-publish-cnm"
version = "1.0.1a17"
description = "Publishes CNM to ingest SoS granules"
authors = [
    {name = "Nikki",email = "17799906+nikki-t@users.noreply.github.com"}
]
license = {text = "Apache License 2.0"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "boto3 (>=1.37.38,<2.0.0)",
    "netcdf4 (>=1.7.2,<2.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [
    {include = "publish_cnm.py"}
]

[tool.poetry.scripts]
publish_cnm = 'publish_cnm:main'